/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF("/room.glb");
	return (
		<group ref={group} {...props} dispose={null}>
			<group position={[0.68, 2.78, -5.06]} scale={[3.52, 2.56, 2.84]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.WindowFrame.geometry}
					material={nodes.WindowFrame.material}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.WindowL.geometry}
						material={nodes.WindowL.material}
						position={[-0.59, 0.03, 0.02]}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Handle.geometry}
							material={nodes.Handle.material}
							position={[0.04, 0.47, 0.04]}
						/>
					</mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.WindowR.geometry}
						material={nodes.WindowR.material}
						position={[0.59, 0.03, 0.06]}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Handle001.geometry}
							material={nodes.Handle001.material}
							position={[-0.04, 0.47, 0.04]}
						/>
					</mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Windows_Sill.geometry}
						material={materials.Sill_material}
						position={[0, 0, 0.1]}
					/>
				</mesh>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Desk_Regular.geometry}
				material={materials.desktest}
				position={[-1.84, 1.52, -3.7]}
				rotation={[0, 1.56, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shelves_Floating.geometry}
				material={materials["Material.010"]}
				position={[4.33, 4.01, 3.07]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Katana_Blade_Seperater.geometry}
				material={materials["Material.033"]}
				position={[4.37, 5.31, 2.16]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.TV.geometry}
				material={materials["None.008"]}
				position={[4.55, 2.78, 3.06]}
				rotation={[Math.PI / 2, -0.07, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Monitors_Quad.geometry}
				material={materials["Material.043"]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Matress.geometry}
				material={materials["Material.008"]}
				position={[3.33, 0.59, -1.62]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={[2.6, 0.97, 0.97]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Bed_Frame.geometry}
				material={materials["Material.009"]}
				position={[2.94, -0.16, -1.71]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={[2.91, 1.59, 1.83]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Walls.geometry}
				material={materials["Material.013"]}
				scale={[4.77, 4.77, 4.77]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Eth_Statue.geometry}
				material={materials["Material.028"]}
				position={[4.29, 4.55, 3.12]}
				rotation={[Math.PI / 2, 0, -0.97]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Case.geometry}
				material={materials["Material.035"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rug.geometry}
				material={materials["Material.024"]}
				position={[2.72, 0.12, 3.01]}
				rotation={[0, Math.PI / 2, 0]}
				scale={[1.17, 0.9, 0.9]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Floor.geometry}
				material={materials["Material.005"]}
				position={[0, -0.01, 0]}
				scale={[4.78, 4.78, 4.78]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Pillows.geometry}
				material={materials["Material.007"]}
				position={[3.74, 1.37, -3.9]}
				rotation={[-0.25, 1.56, 0.52]}
				scale={[0.55, 0.73, 0.89]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Katana_Stands.geometry}
				material={materials["Material.034"]}
				position={[0, 1.13, 1.01]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Power_Supply.geometry}
				material={nodes.PC_Power_Supply.material}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Graphics_Card.geometry}
				material={materials["Material.016"]}
				position={[-4.04, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_CPU.geometry}
				material={materials["Material.037"]}
				position={[-3.78, 5.09, -4.67]}
				scale={[0.48, 0.2, 0.4]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Fans.geometry}
				material={materials["Material.040"]}
				position={[-3.04, 4.63, -4.52]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<group
				position={[-0.24, 0.34, 3.01]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={[1.32, 1.32, 1.32]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder.geometry}
					material={materials.None}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_1.geometry}
					material={materials["Material.036"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Shelf.geometry}
				material={materials["Material.011"]}
				position={[-4.05, 4.42, -4.5]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Window.geometry}
				material={materials["Material.012"]}
				position={[0.92, 3.95, -5.05]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[2.32, 1.98, 1.49]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.TV_Screen.geometry}
				material={materials["Material.014"]}
				position={[4.53, 2.78, 3.06]}
				rotation={[Math.PI / 2, -0.06, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_1.geometry}
				material={materials["Material.017"]}
				position={[4.32, 4.42, 2.07]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mouse_and_Keyboard.geometry}
				material={materials["Material.045"]}
				position={[-0.9, 1.65, -3.26]}
				rotation={[1.58, -0.01, -1.97]}
				scale={[-0.02, 0, -0.02]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_1_Pages.geometry}
				material={materials["None.006"]}
				position={[4.32, 4.42, 2.07]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Blanket.geometry}
				material={materials["Material.006"]}
				position={[2.85, 1.8, -1.35]}
				rotation={[0.11, 0, 0]}
				scale={[2.28, 2.28, 2.98]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_2_Pages.geometry}
				material={materials["None.009"]}
				position={[4.32, 4.42, 2.23]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sofa_Curved_Legs.geometry}
				material={materials["Material.039"]}
				position={[-0.24, 0.34, 3.01]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={[1.32, 1.32, 1.32]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_2.geometry}
				material={materials["Material.018"]}
				position={[4.32, 4.42, 2.23]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_3.geometry}
				material={materials["Material.019"]}
				position={[4.32, 4.42, 2.49]}
				rotation={[1.23, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Eth_Statue_Bottom.geometry}
				material={materials["None.007"]}
				position={[4.29, 4.55, 3.12]}
				rotation={[Math.PI / 2, 0, -0.97]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shoe_Box_Bottom.geometry}
				material={materials["Material.029"]}
				position={[4.32, 4.39, 3.88]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shoe_Box_Top.geometry}
				material={materials["None.012"]}
				position={[4.32, 4.39, 3.88]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_3_Pages.geometry}
				material={materials["None.011"]}
				position={[4.32, 4.42, 2.49]}
				rotation={[1.23, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Katana_Blade.geometry}
				material={materials["Material.030"]}
				position={[4.37, 5.3, 3.77]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Katana_Handle.geometry}
				material={materials["Material.032"]}
				position={[4.37, 5.3, 1.73]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Motherboard.geometry}
				material={materials["Material.038"]}
				position={[-3.6, 5.09, -4.71]}
				scale={[0.33, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Above_Power_Supply.geometry}
				material={materials["Material.022"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Ram_Sticks.geometry}
				material={materials["Material.041"]}
				position={[-3.33, 5.11, -4.65]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Above_Power_Supply_2.geometry}
				material={nodes.PC_Above_Power_Supply_2.material}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Case002.geometry}
				material={materials["Material.051"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_CPU001.geometry}
				material={materials["Material.026"]}
				position={[-3.78, 5.09, -4.67]}
				scale={[0.48, 0.2, 0.4]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Monitor_Screens_Quad_.geometry}
				material={materials["None.003"]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_CPU_Actual001.geometry}
				material={materials["Material.042"]}
				position={[-3.78, 5.09, -4.67]}
				scale={[0.48, 0.2, 0.4]}
			/>
			<group
				position={[-1.51, 1.62, -3.21]}
				rotation={[1.58, -0.01, -1.97]}
				scale={[-0.02, 0, -0.02]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder003.geometry}
					material={materials["Material.046"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder003_1.geometry}
					material={materials["Material.056"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder003_2.geometry}
					material={materials["Material.058"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Eth_Statue_Bottom_2.geometry}
				material={materials["Material.002"]}
				position={[4.29, 4.55, 3.12]}
				rotation={[Math.PI / 2, 0, -0.97]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Case001.geometry}
				material={materials["Material.003"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Graphics_LED.geometry}
				material={nodes.PC_Graphics_LED.material}
				position={[-4.04, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Fan_LED003.geometry}
				material={nodes.PC_Fan_LED003.material}
				position={[-3.04, 4.63, -4.52]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_RAM_LED.geometry}
				material={nodes.PC_RAM_LED.material}
				position={[-3.33, 5.11, -4.63]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_CPU_Actual.geometry}
				material={materials["Material.020"]}
				position={[-3.78, 5.09, -4.67]}
				scale={[0.48, 0.2, 0.4]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Ram_Sticks001.geometry}
				material={materials["Material.001"]}
				position={[-3.33, 5.11, -4.65]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Fan_LED.geometry}
				material={nodes.PC_Fan_LED.material}
				position={[-3.04, 4.63, -4.52]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Case003.geometry}
				material={materials["Material.053"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Above_Power_Supply001.geometry}
				material={materials["Material.055"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Above_Power_Supply_2001.geometry}
				material={materials["Material.054"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Fan_LED001.geometry}
				material={nodes.PC_Fan_LED001.material}
				position={[-3.52, 4.33, -4.52]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Fan_LED002.geometry}
				material={nodes.PC_Fan_LED002.material}
				position={[-3.52, 4.33, -4.52]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Fans001.geometry}
				material={materials["Material.021"]}
				position={[-3.04, 4.63, -4.52]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Graphics_Card001.geometry}
				material={materials["Material.048"]}
				position={[-4.04, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Graphics_LED001.geometry}
				material={nodes.PC_Graphics_LED001.material}
				position={[-4.04, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Motherboard001.geometry}
				material={materials["Material.025"]}
				position={[-3.6, 5.09, -4.71]}
				scale={[0.33, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Power_Supply001.geometry}
				material={materials["Material.031"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_RAM_LED001.geometry}
				material={nodes.PC_RAM_LED001.material}
				position={[-3.33, 5.11, -4.63]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Shelf001.geometry}
				material={materials["Material.050"]}
				position={[-4.05, 4.42, -4.5]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.PC_Case004.geometry}
				material={materials["Material.052"]}
				position={[-4.05, 4.42, -4.54]}
				scale={[0.28, 0.12, 0.23]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mouse.geometry}
				material={materials["Material.044"]}
				position={[-0.9, 1.65, -3.26]}
				rotation={[1.58, -0.01, -1.97]}
				scale={[-0.02, 0, -0.02]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Eth_Neon_Sign.geometry}
				material={materials["Material.027"]}
				position={[-0.02, -0.16, 0]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/room.glb");
